### PR TITLE
Mastering for Google fonts (Round 1)

### PR DESCRIPTION
**Pull request by m4rc1e**
I've just gone through your repo and made the necessary changes in order for us to host this project.

Whilst working on it, I've discovered that the following glyphs are missing:

guillemotleft | «
-- | --
section | §
uni2126 | Ω
uni2206 | ∆

glyphs_missing

Please can you add them and then I will carry on mastering

### CODE REVIEW

**Comment by VivaRado** [comment]
That was just addressed!

Glyphs: OHM, INCREMENT, guillemotleft, section, where added

**Review by VivaRado — DISMISSED** [review]
Great!

**Comment by m4rc1e** [comment]
Eugh. The latest file you pushed trashed this pr and there are still glyph incompatibilities with your latest push!

Screenshot 2022-01-25 at 10 31 31

**Comment by VivaRado** [comment]
Works on my side. 

By using https://github.com/VivaRado/Advent/tree/master/font_source/UFOs/latest/advent_pro

And running the SH to compile, you can see the new variable favors generated.

The renamed VAR/adventpro-def-VF.ttf (definitive) or AdventPro[ital,wdth,wght].ttf as you call it for Mastering, is newly generated from the UFOs provided.

If your PR breaks then I guess you'll have to sync with master again.

**Pull request closed without merging**
